---
- name: A playbook that will perform a graceful restart via RedFish APIs using the community.general collection
  hosts: redfish_apis    # group name
  connection: local      # we need to run HTTP(s) to talk to the RedFish APIs
  gather_facts: false

  # collections:
  # - community.general      # to update / install, "ansible-galaxy collection install community.general"

  tasks:
        - name: Restart system power gracefully
          community.general.redfish_command:
            category: Systems
            command: PowerGracefulRestart
            baseuri: "{{ baseuri }}"
            username: "{{ username }}"
            password: "{{ password }}"

